### ISSUE TITLE
Installing this extension in CiviCRM 4.7 gives an error

### ISSUE THREAD

**Issue by jaapjansma** [systopia/de.systopia.identitytracker#2]
Installing this extension gives the following database error: '1292 - Truncated incorrect DOUBLE value'

Removing line 55 from CRM/Identitytracker/Migration.php fixes it line 39 and following looks like:

`CRM_Core_DAO::executeQuery("
      INSERT INTO `$group_table` (`entity_id`, `{$type_column}`, `{$id_column}`, `{$date_column}`)
        (SELECT  id AS ch_entity_id,
                 %1 AS ch_type,
                 `{$contact_field}` AS ch_indentifier,
                 COALESCE (DATE(`created_date`), DATE(%2)) AS ch_date
          FROM   `civicrm_contact`
          WHERE  `{$contact_field}` IS NOT NULL
            AND  `{$contact_field}` IS != ''
            AND  NOT EXISTS ( SELECT `{$group_table}`.`id` FROM `{$group_table}` 
                               WHERE `entity_id` = `civicrm_contact`.`id`
                                 AND `{$type_column}` = %1
                                 AND `{$id_column}` = `civicrm_contact`.`{$contact_field}`)
        );", array(
            1 => array($type, 'String'),
            2 => array($install_date, 'String'),
        ));`

Removing 

`AND  `{$contact_field}` IS != ''` fixes it

**Comment by bjendres** [comment]
@jaapjansma: Where again is that code you want to change? I couldn't find ``IS != '' `` anywhere in the code...

Could you illustrate with a PR?

**Comment by jaapjansma** [comment]
It is on this line: https://github.com/systopia/de.systopia.identitytracker/blob/master/CRM/Identitytracker/Migration.php#L47

I am more than happy to provide a PR however I am not sure whether removing that lines does not breal anything else.

**Comment by bjendres** [comment]
But the line says
``
AND `{$contact_field}` != ''
``
and not 
``
AND `{$contact_field}` IS != ''
``

I'm asking because I can also not reproduce the issue when installing on a fresh 4.7.17. Which version are you using? Are you sure there's no modifications, e.g. change of DB data type of ``civicrm_contact.external_identifier``?

**Comment by jaapjansma** [comment]
I installed in civicrm 4.7.16. Maybe the error was caused by other customisations of in that installation. So I would say if it works in 4.7.17 it has probably something to do with this specific installation. Rather than a bug in identitytracker.

**Comment by jaapjansma** [comment]
@systopia thank anyway for this extension!

**Comment by bjendres** [comment]
Thanks. Glad to hear people are using it :)
