### ISSUE TITLE
PHP notice after updating a membership

### ISSUE THREAD

**Issue by michaelmcandrew** [systopia/de.systopia.identitytracker#4]
When installed (but not configured - not sure if that is relevant) I get a Notice: Undefined index: group in civicrm_api3_setting_getvalue() (line 329 of ###drupal/sites/all/modules/civicrm/api/v3/Setting.php) notice popping up after updating a membership.

It seems to be coming from

```
  public function getCustomFieldMapping() {
    return civicrm_api3('Setting', 'getvalue', array('name' => 'identitytracker_mapping'));
  }
```

Minor issue but good to keep notices down to 0 to help with debugging / developing.

**Comment by bjendres** [comment]
@michaelmcandrew could you confirm that https://github.com/systopia/de.systopia.identitytracker/commit/c807cb8f1e51703925d41d9b2356657f242f9be8 fixes that?

**Comment by michaelmcandrew** [comment]
hey @systopia - i can confirm that when updating a membership with the latest version of the contract extension and the latest master of this extension, I no longer get the warning

**Comment by bjendres** [comment]
Great, thanks
